# Default values for ex-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deploymentName: app-deployment
image:
  repository:
    apache: httpd
    nginx: nginx
  pullPolicy: IfNotPresent
  containerPort: 80

resources:
  requests:
    cpu: "50m"
    memory: "60Mi"
    
selectorLabels:
  app: "test"

service:
  port: 80
  targetPort: 80
  nodePort: 30007
  type: NodePort